version: 19
jobs:
- name: Run PyTest
  steps:
  - !CommandStep
    name: Run PyTest
    runInContainer: true
    image: python:3.10
    interpreter: !DefaultInterpreter
      commands:
      - pip install -U pytest
      - pytest
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !BuildImageStep
    name: Build Docker Image
    tags: '@build_number@_pr@pull_request_number@'
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !PullRequestUpdateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: Build Docker Image
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
stepTemplates:
- name: Build Docker Image
  steps:
  - !BuildImageStep
    name: Build Docker Image
    tags: '@branch@ @pull_request_number@ @project_name@ @tag@'
    publish: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
